name: Deploy to Firebase Hosting

#  Run this workflow every time I push to the 'main' branch
on:
  push:
    branches:
      - main 

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Downloads code from repo
      - name: Checkout Code
        uses: actions/checkout@v4

      # Deploys to Firebase using key
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_TOKEN }}
          channelId: live
          projectId: "mitin-das" 
          force: true # Firebase API bug, not my fault it thinks 
                      # the Github release is the same as previous :/
